### ISSUE TITLE
Support custom ROS2 messages

### ISSUE THREAD

**Issue by nehamaerez** [facontidavide/plotjuggler-release#1]
Hi,
I have some custom ROS (2) messages that I would like to plot in plotjuggler.
Currently, I can see the topics but nothing happens when I select them. Of course, standard ROS messages are working fine (geometry_msgs etc.).
Could you recommend the best way to add my custom messages?

**Comment by facontidavide** [comment]
do not submit issues here. But in https://github.com/PlotJuggler/plotjuggler-ros-plugins instead
